name: Update Society Data
on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Update data files
      run: |
        # This would call your Google Apps Script web app to get latest data
        # You'll need to create a web app endpoint in GAS
        echo "Data update would happen here"
        # curl -X POST "YOUR_GAS_WEB_APP_URL" -o data/latest.json
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Auto-update society data" || exit 0
        git push